# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrei/Documents/Programming/Projects/CityBuilder_Network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrei/Documents/Programming/Projects/CityBuilder_Network

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/Programming/Projects/CityBuilder_Network/CMakeFiles /home/andrei/Documents/Programming/Projects/CityBuilder_Network/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrei/Documents/Programming/Projects/CityBuilder_Network/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClientMain

# Build rule for target.
ClientMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClientMain
.PHONY : ClientMain

# fast build rule for target.
ClientMain/fast:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/build
.PHONY : ClientMain/fast

#=============================================================================
# Target rules for targets named ServerMain

# Build rule for target.
ServerMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ServerMain
.PHONY : ServerMain

# fast build rule for target.
ServerMain/fast:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/build
.PHONY : ServerMain/fast

Source/Client/Client.o: Source/Client/Client.cpp.o

.PHONY : Source/Client/Client.o

# target to build an object file
Source/Client/Client.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Client.cpp.o
.PHONY : Source/Client/Client.cpp.o

Source/Client/Client.i: Source/Client/Client.cpp.i

.PHONY : Source/Client/Client.i

# target to preprocess a source file
Source/Client/Client.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Client.cpp.i
.PHONY : Source/Client/Client.cpp.i

Source/Client/Client.s: Source/Client/Client.cpp.s

.PHONY : Source/Client/Client.s

# target to generate assembly for a file
Source/Client/Client.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Client.cpp.s
.PHONY : Source/Client/Client.cpp.s

Source/Client/ClientMain.o: Source/Client/ClientMain.cpp.o

.PHONY : Source/Client/ClientMain.o

# target to build an object file
Source/Client/ClientMain.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/ClientMain.cpp.o
.PHONY : Source/Client/ClientMain.cpp.o

Source/Client/ClientMain.i: Source/Client/ClientMain.cpp.i

.PHONY : Source/Client/ClientMain.i

# target to preprocess a source file
Source/Client/ClientMain.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/ClientMain.cpp.i
.PHONY : Source/Client/ClientMain.cpp.i

Source/Client/ClientMain.s: Source/Client/ClientMain.cpp.s

.PHONY : Source/Client/ClientMain.s

# target to generate assembly for a file
Source/Client/ClientMain.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/ClientMain.cpp.s
.PHONY : Source/Client/ClientMain.cpp.s

Source/Client/Interface.o: Source/Client/Interface.cpp.o

.PHONY : Source/Client/Interface.o

# target to build an object file
Source/Client/Interface.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Interface.cpp.o
.PHONY : Source/Client/Interface.cpp.o

Source/Client/Interface.i: Source/Client/Interface.cpp.i

.PHONY : Source/Client/Interface.i

# target to preprocess a source file
Source/Client/Interface.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Interface.cpp.i
.PHONY : Source/Client/Interface.cpp.i

Source/Client/Interface.s: Source/Client/Interface.cpp.s

.PHONY : Source/Client/Interface.s

# target to generate assembly for a file
Source/Client/Interface.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Interface.cpp.s
.PHONY : Source/Client/Interface.cpp.s

Source/Client/Menu.o: Source/Client/Menu.cpp.o

.PHONY : Source/Client/Menu.o

# target to build an object file
Source/Client/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Menu.cpp.o
.PHONY : Source/Client/Menu.cpp.o

Source/Client/Menu.i: Source/Client/Menu.cpp.i

.PHONY : Source/Client/Menu.i

# target to preprocess a source file
Source/Client/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Menu.cpp.i
.PHONY : Source/Client/Menu.cpp.i

Source/Client/Menu.s: Source/Client/Menu.cpp.s

.PHONY : Source/Client/Menu.s

# target to generate assembly for a file
Source/Client/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Client/Menu.cpp.s
.PHONY : Source/Client/Menu.cpp.s

Source/Server/Server.o: Source/Server/Server.cpp.o

.PHONY : Source/Server/Server.o

# target to build an object file
Source/Server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/Server.cpp.o
.PHONY : Source/Server/Server.cpp.o

Source/Server/Server.i: Source/Server/Server.cpp.i

.PHONY : Source/Server/Server.i

# target to preprocess a source file
Source/Server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/Server.cpp.i
.PHONY : Source/Server/Server.cpp.i

Source/Server/Server.s: Source/Server/Server.cpp.s

.PHONY : Source/Server/Server.s

# target to generate assembly for a file
Source/Server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/Server.cpp.s
.PHONY : Source/Server/Server.cpp.s

Source/Server/ServerMain.o: Source/Server/ServerMain.cpp.o

.PHONY : Source/Server/ServerMain.o

# target to build an object file
Source/Server/ServerMain.cpp.o:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/ServerMain.cpp.o
.PHONY : Source/Server/ServerMain.cpp.o

Source/Server/ServerMain.i: Source/Server/ServerMain.cpp.i

.PHONY : Source/Server/ServerMain.i

# target to preprocess a source file
Source/Server/ServerMain.cpp.i:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/ServerMain.cpp.i
.PHONY : Source/Server/ServerMain.cpp.i

Source/Server/ServerMain.s: Source/Server/ServerMain.cpp.s

.PHONY : Source/Server/ServerMain.s

# target to generate assembly for a file
Source/Server/ServerMain.cpp.s:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/ServerMain.cpp.s
.PHONY : Source/Server/ServerMain.cpp.s

Source/Server/User.o: Source/Server/User.cpp.o

.PHONY : Source/Server/User.o

# target to build an object file
Source/Server/User.cpp.o:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/User.cpp.o
.PHONY : Source/Server/User.cpp.o

Source/Server/User.i: Source/Server/User.cpp.i

.PHONY : Source/Server/User.i

# target to preprocess a source file
Source/Server/User.cpp.i:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/User.cpp.i
.PHONY : Source/Server/User.cpp.i

Source/Server/User.s: Source/Server/User.cpp.s

.PHONY : Source/Server/User.s

# target to generate assembly for a file
Source/Server/User.cpp.s:
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Server/User.cpp.s
.PHONY : Source/Server/User.cpp.s

Source/Shared/City.o: Source/Shared/City.cpp.o

.PHONY : Source/Shared/City.o

# target to build an object file
Source/Shared/City.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/City.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/City.cpp.o
.PHONY : Source/Shared/City.cpp.o

Source/Shared/City.i: Source/Shared/City.cpp.i

.PHONY : Source/Shared/City.i

# target to preprocess a source file
Source/Shared/City.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/City.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/City.cpp.i
.PHONY : Source/Shared/City.cpp.i

Source/Shared/City.s: Source/Shared/City.cpp.s

.PHONY : Source/Shared/City.s

# target to generate assembly for a file
Source/Shared/City.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/City.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/City.cpp.s
.PHONY : Source/Shared/City.cpp.s

Source/Shared/Enums.o: Source/Shared/Enums.cpp.o

.PHONY : Source/Shared/Enums.o

# target to build an object file
Source/Shared/Enums.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Enums.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Enums.cpp.o
.PHONY : Source/Shared/Enums.cpp.o

Source/Shared/Enums.i: Source/Shared/Enums.cpp.i

.PHONY : Source/Shared/Enums.i

# target to preprocess a source file
Source/Shared/Enums.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Enums.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Enums.cpp.i
.PHONY : Source/Shared/Enums.cpp.i

Source/Shared/Enums.s: Source/Shared/Enums.cpp.s

.PHONY : Source/Shared/Enums.s

# target to generate assembly for a file
Source/Shared/Enums.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Enums.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Enums.cpp.s
.PHONY : Source/Shared/Enums.cpp.s

Source/Shared/Memory.o: Source/Shared/Memory.cpp.o

.PHONY : Source/Shared/Memory.o

# target to build an object file
Source/Shared/Memory.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Memory.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Memory.cpp.o
.PHONY : Source/Shared/Memory.cpp.o

Source/Shared/Memory.i: Source/Shared/Memory.cpp.i

.PHONY : Source/Shared/Memory.i

# target to preprocess a source file
Source/Shared/Memory.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Memory.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Memory.cpp.i
.PHONY : Source/Shared/Memory.cpp.i

Source/Shared/Memory.s: Source/Shared/Memory.cpp.s

.PHONY : Source/Shared/Memory.s

# target to generate assembly for a file
Source/Shared/Memory.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Memory.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Memory.cpp.s
.PHONY : Source/Shared/Memory.cpp.s

Source/Shared/Scene.o: Source/Shared/Scene.cpp.o

.PHONY : Source/Shared/Scene.o

# target to build an object file
Source/Shared/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Scene.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Scene.cpp.o
.PHONY : Source/Shared/Scene.cpp.o

Source/Shared/Scene.i: Source/Shared/Scene.cpp.i

.PHONY : Source/Shared/Scene.i

# target to preprocess a source file
Source/Shared/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Scene.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Scene.cpp.i
.PHONY : Source/Shared/Scene.cpp.i

Source/Shared/Scene.s: Source/Shared/Scene.cpp.s

.PHONY : Source/Shared/Scene.s

# target to generate assembly for a file
Source/Shared/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Scene.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Scene.cpp.s
.PHONY : Source/Shared/Scene.cpp.s

Source/Shared/Utility.o: Source/Shared/Utility.cpp.o

.PHONY : Source/Shared/Utility.o

# target to build an object file
Source/Shared/Utility.cpp.o:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Utility.cpp.o
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Utility.cpp.o
.PHONY : Source/Shared/Utility.cpp.o

Source/Shared/Utility.i: Source/Shared/Utility.cpp.i

.PHONY : Source/Shared/Utility.i

# target to preprocess a source file
Source/Shared/Utility.cpp.i:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Utility.cpp.i
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Utility.cpp.i
.PHONY : Source/Shared/Utility.cpp.i

Source/Shared/Utility.s: Source/Shared/Utility.cpp.s

.PHONY : Source/Shared/Utility.s

# target to generate assembly for a file
Source/Shared/Utility.cpp.s:
	$(MAKE) -f CMakeFiles/ClientMain.dir/build.make CMakeFiles/ClientMain.dir/Source/Shared/Utility.cpp.s
	$(MAKE) -f CMakeFiles/ServerMain.dir/build.make CMakeFiles/ServerMain.dir/Source/Shared/Utility.cpp.s
.PHONY : Source/Shared/Utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ClientMain"
	@echo "... ServerMain"
	@echo "... Source/Client/Client.o"
	@echo "... Source/Client/Client.i"
	@echo "... Source/Client/Client.s"
	@echo "... Source/Client/ClientMain.o"
	@echo "... Source/Client/ClientMain.i"
	@echo "... Source/Client/ClientMain.s"
	@echo "... Source/Client/Interface.o"
	@echo "... Source/Client/Interface.i"
	@echo "... Source/Client/Interface.s"
	@echo "... Source/Client/Menu.o"
	@echo "... Source/Client/Menu.i"
	@echo "... Source/Client/Menu.s"
	@echo "... Source/Server/Server.o"
	@echo "... Source/Server/Server.i"
	@echo "... Source/Server/Server.s"
	@echo "... Source/Server/ServerMain.o"
	@echo "... Source/Server/ServerMain.i"
	@echo "... Source/Server/ServerMain.s"
	@echo "... Source/Server/User.o"
	@echo "... Source/Server/User.i"
	@echo "... Source/Server/User.s"
	@echo "... Source/Shared/City.o"
	@echo "... Source/Shared/City.i"
	@echo "... Source/Shared/City.s"
	@echo "... Source/Shared/Enums.o"
	@echo "... Source/Shared/Enums.i"
	@echo "... Source/Shared/Enums.s"
	@echo "... Source/Shared/Memory.o"
	@echo "... Source/Shared/Memory.i"
	@echo "... Source/Shared/Memory.s"
	@echo "... Source/Shared/Scene.o"
	@echo "... Source/Shared/Scene.i"
	@echo "... Source/Shared/Scene.s"
	@echo "... Source/Shared/Utility.o"
	@echo "... Source/Shared/Utility.i"
	@echo "... Source/Shared/Utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

